# Generated by Django 3.2.9 on 2021-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_images_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='type',
            field=models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt')], max_length=40),
        ),
    ]
